services:
  gig-dicionario-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3742:3742"
    volumes:
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
    environment:
      - CHOKIDAR_USEPOLLING=true
